### ISSUE TITLE
Add jinja filter to read envionment variables.

### ISSUE THREAD

**Issue by adobe-jeremy** [adobe/buildrunner#102]
Would there be any appetite in support a jinja filter to read arbitrary environments variables?  I have code and unit tests done to support this, but the PR template directed me to create an issue first.

I particularly would like this functionality as it cuts down on pre buildrunner steps that may require renaming variables with BUILDRUNNER_*.  Specifically for me, it would be AWS creds that need to be passed in to a steps container.

Example:
```
AWS_ACCESS_KEY_ID: "{{ env('AWS_ACCESS_KEY_ID') }}"
```

**Comment by bluesliverx** [comment]
This is an elegant solution to something that's bothered me for awhile. The only problem I have with it is that I didn't think of it sooner :)

This is implemented in the linked PR, take a look and let me know if that looks ok.

**Comment by adobe-jeremy** [comment]
> This is an elegant solution to something that's bothered me for awhile. The only problem I have with it is that I didn't think of it sooner :)
> 
> This is implemented in the linked PR, take a look and let me know if that looks ok.

LGTM!  Thanks, this is going to make things so much easier.

**Comment by bluesliverx** [comment]
No problem, it should be released to the build servers tonight (but is available from pypi right now).
